/**
 * Zedi Extension config (Service Worker) - generated by prepare-extension.js
 * Do not edit manually. Run: bun run prepare:extension:dev | prepare:extension:prod
 */
self.ZEDI_EXT_CONFIG = { API_BASE_URL: "https://zedi-note.app" };
