/**
 * Zedi Extension config - generated by prepare-extension.js
 * Do not edit manually. Run: bun run prepare:extension:dev | prepare:extension:prod
 */
window.ZEDI_EXT_CONFIG = { API_BASE_URL: "https://zedi-note.app" };
